[package]
name = "yaytracer"
version = "0.1.0"
authors = ["tomha"]
edition = "2018"

[dependencies]
image = "0.21.0"
rand = "0.6.5"
cgmath = "0.17.0"
md5 = "0.6.1"
indicatif = "0.11.0"
threadpool = "1.7.1"